sonar.projectKey=greenkerokero_python-project-52
sonar.organization=greenkerokerokey29
sonar.sources=task_manager
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/migrations/**, **/settings.py, **/manage.py, **/tests.py, **/tests/**, **/wsgi.py, **/asgi.py, **/apps.py, **/management/commands/**
sonar.tests=task_manager
sonar.test.inclusions=**/tests.py, **/tests/**