# Generated by Django 6.0.3 on 2026-04-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_label_created_at_label_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(error_messages={'unique': 'Label with this Name already exists'}, max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
