name: Python CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.14" ]
    env:
      SECRET_KEY: "secret-key-for-github-actions"
      ROLLBAR_ACCESS_TOKEN: "rollbar-token"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install uv
          make install

      - name: Run linter
        run:
          make lint

      - name: Run tests with coverage
        run: |
          make test-coverage
          uv run coverage xml

      - name: SonarQube
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
