# Generated by Django 6.0.3 on 2026-05-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default Status'),
        ),
    ]
